import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [id, setId] = useState(0);
  const [serverId, setServerId] = useState(0);
  const [channelId, setChannelId] = useState(0);

  const [users, setUsers] = useState([]);
  const [servers, setServers] = useState([]);
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    fetch("http://localhost:3000/users").then((res) => {
      res.json().then((users) => {
        setUsers(users);
        setServers(users.servers);
      });
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>users</div>
        {users.map((val, _) => (
          <button
            onClick={() => {
              setId(val._id);
              localStorage.setItem("id", val._id);
            }}
          >
            {val.name}
          </button>
        ))}

        <div>servers</div>
        {servers?.map((val, _) => (
          <button
            onClick={() => {
              setServerId(val._id);
              setMessages(val.messages);
            }}
          >
            {val.name}
          </button>
        ))}

        {messages.map((val, _) => (
          <div>{val.content}</div>
        ))}

        <div>{id}</div>
        <button
          onClick={() => {
            fetch("http://localhost:3000/users", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ name: "sam_" }),
            }).then((res) => {
              res.json().then((user) => {
                setId(user._id);
              });
            });
          }}
        >
          Create User
        </button>

        <div>{serverId}</div>
        <button
          onClick={() => {
            fetch("http://localhost:3000/servers", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ name: "Tech Den", owner: id }),
            }).then((res) => {
              res.json().then((server) => {
                setServerId(server._id);
              });
            });
          }}
        >
          Create Server
        </button>

        <div>{channelId}</div>
        <button
          onClick={() => {
            fetch("http://localhost:3000/messages", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                content: "general",
                author: id,
                server: serverId,
              }),
            }).then((res) => {
              res.json().then((channel) => {
                setChannelId(JSON.stringify(channel));
              });
            });
          }}
        >
          Create Message
        </button>
      </main>
    </div>
  );
};

export default Home;
